version: "3.9"
services:
  spinnyboi:
    image: tyleragostino/spinnyboi:latest
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GSHEET_ID=${GSHEET_ID}
  ollama:
    image: tyleragostino/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
        - ollama:/root/.ollama
volumes:
  ollama: